{{- if and .Values.appSettings.requireApiKeySecret (not .Values.appSettings.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "libretranslate.fullname" . }}-api-key
type: Opaque
data:
  requireApiKeySecret: {{ .Values.appSettings.requireApiKeySecret | quote }}
{{- end }}
